# Connexion PostgreSQL
DB_HOST=localhost
DB_PORT=5432
DB_NAME=air_quality_dw
DB_USER=postgres
DB_PASS=

# APIs
OPENAQ_URL=https://api.openaq.org/v2/measurements
OPENMETEO_URL=https://api.open-meteo.com/v1/forecast

# Villes à analyser (latitude,longitude,nom)
VILLES=Paris,London,Berlin,Madrid,Tunis,Cairo,Delhi,Beijing,New York,São Paulo
