-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_meteo_classe
(
    id_meteo_classe serial NOT NULL,
    temp_bande character varying(20) COLLATE pg_catalog."default" NOT NULL,
    humidite_bande character varying(20) COLLATE pg_catalog."default" NOT NULL,
    vent_bande character varying(20) COLLATE pg_catalog."default" NOT NULL,
    pluie_classe character varying(20) COLLATE pg_catalog."default" NOT NULL,
    source_classe character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_meteo_classe_pkey PRIMARY KEY (id_meteo_classe),
    CONSTRAINT dim_meteo_classe_unique UNIQUE (temp_bande, humidite_bande, vent_bande, pluie_classe, source_classe)
);

COMMENT ON TABLE public.dim_meteo_classe
    IS 'Classes discrètes des conditions météo pour analyse par groupe';

CREATE TABLE IF NOT EXISTS public.dim_pays
(
    id_pays serial NOT NULL,
    pays_code character(3) COLLATE pg_catalog."default" NOT NULL,
    pays_nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    continent character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT dim_pays_pkey PRIMARY KEY (id_pays),
    CONSTRAINT dim_pays_pays_code_key UNIQUE (pays_code)
);

CREATE TABLE IF NOT EXISTS public.dim_station
(
    id_station serial NOT NULL,
    station_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    station_nom character varying(150) COLLATE pg_catalog."default" NOT NULL,
    ville character varying(100) COLLATE pg_catalog."default" NOT NULL,
    latitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    altitude_m smallint,
    type_zone character varying(30) COLLATE pg_catalog."default" NOT NULL,
    timezone_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_pays integer NOT NULL,
    CONSTRAINT dim_station_pkey PRIMARY KEY (id_station),
    CONSTRAINT dim_station_station_code_key UNIQUE (station_code)
);

COMMENT ON TABLE public.dim_station
    IS 'Stations de mesure physiques source OpenAQ';

COMMENT ON COLUMN public.dim_station.type_zone
    IS 'Contexte géographique du capteur';

CREATE TABLE IF NOT EXISTS public.dim_temps
(
    id_temps serial NOT NULL,
    date_heure_utc timestamp without time zone NOT NULL,
    date_locale date NOT NULL,
    annee smallint NOT NULL,
    trimestre smallint NOT NULL,
    mois smallint NOT NULL,
    semaine smallint NOT NULL,
    jour smallint NOT NULL,
    heure smallint NOT NULL,
    jour_semaine character varying(10) COLLATE pg_catalog."default" NOT NULL,
    is_weekend boolean NOT NULL DEFAULT false,
    saison character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dim_temps_pkey PRIMARY KEY (id_temps),
    CONSTRAINT dim_temps_date_heure_utc_key UNIQUE (date_heure_utc)
);

COMMENT ON TABLE public.dim_temps
    IS 'Dimension temporelle à granularité horaire';

COMMENT ON COLUMN public.dim_temps.is_weekend
    IS 'TRUE si samedi ou dimanche';

COMMENT ON COLUMN public.dim_temps.saison
    IS 'Saison astronomique dérivée du mois';

CREATE TABLE IF NOT EXISTS public.fait_pollution_heure
(
    id_fait bigserial NOT NULL,
    id_temps integer NOT NULL,
    id_station integer NOT NULL,
    id_meteo_classe integer,
    co_mg_m3 numeric(10, 4),
    no2_ug_m3 numeric(10, 4),
    pm25_ug_m3 numeric(10, 4),
    pm10_ug_m3 numeric(10, 4),
    o3_ug_m3 numeric(10, 4),
    benzene_ug_m3 numeric(10, 4),
    nox_ppb numeric(10, 4),
    indice_aqi smallint,
    seuil_oms_depasse boolean NOT NULL DEFAULT false,
    temperature_c numeric(6, 2),
    humidite_relative_pct numeric(6, 2),
    vitesse_vent_10m_ms numeric(6, 2),
    precipitation_mm numeric(6, 2) NOT NULL DEFAULT 0,
    rain_flag boolean NOT NULL DEFAULT false,
    charge_le_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fait_pollution_heure_pkey PRIMARY KEY (id_fait),
    CONSTRAINT fait_pollution_heure_id_temps_id_station_key UNIQUE (id_temps, id_station)
);

COMMENT ON TABLE public.fait_pollution_heure
    IS 'Mesures horaires pollution + météo — 1 ligne par station par heure';

COMMENT ON COLUMN public.fait_pollution_heure.indice_aqi
    IS 'AQI calculé par Pentaho basé sur PM2.5 (0=excellent, 500=dangereux)';

CREATE TABLE IF NOT EXISTS public.fait_sante_annuelle
(
    id_fait bigserial NOT NULL,
    id_pays integer NOT NULL,
    annee smallint NOT NULL,
    indicator_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    indicator_nom character varying(200) COLLATE pg_catalog."default",
    indicator_valeur numeric(12, 4),
    who_dim1_code character varying(50) COLLATE pg_catalog."default",
    who_dim1_nom character varying(100) COLLATE pg_catalog."default",
    charge_le_utc timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fait_sante_annuelle_pkey PRIMARY KEY (id_fait),
    CONSTRAINT fait_sante_annuelle_annee_id_pays_indicator_code_key UNIQUE (annee, id_pays, indicator_code)
);

COMMENT ON TABLE public.fait_sante_annuelle
    IS 'Indicateurs santé annuels WHO — 1 ligne par pays par année par indicateur';

COMMENT ON COLUMN public.fait_sante_annuelle.id_pays
    IS 'FK vers dim_pays — dimension partagée avec fait_pollution_heure';

COMMENT ON COLUMN public.fait_sante_annuelle.annee
    IS 'Granularité annuelle WHO — jointure avec dim_temps via t.annee = sante.annee';

ALTER TABLE IF EXISTS public.dim_station
    ADD CONSTRAINT dim_station_id_pays_fkey FOREIGN KEY (id_pays)
    REFERENCES public.dim_pays (id_pays) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_station_pays
    ON public.dim_station(id_pays);


ALTER TABLE IF EXISTS public.fait_pollution_heure
    ADD CONSTRAINT fait_pollution_heure_id_meteo_classe_fkey FOREIGN KEY (id_meteo_classe)
    REFERENCES public.dim_meteo_classe (id_meteo_classe) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fait_pollution_heure
    ADD CONSTRAINT fait_pollution_heure_id_station_fkey FOREIGN KEY (id_station)
    REFERENCES public.dim_station (id_station) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_pollution_station
    ON public.fait_pollution_heure(id_station);


ALTER TABLE IF EXISTS public.fait_pollution_heure
    ADD CONSTRAINT fait_pollution_heure_id_temps_fkey FOREIGN KEY (id_temps)
    REFERENCES public.dim_temps (id_temps) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_pollution_temps
    ON public.fait_pollution_heure(id_temps);


ALTER TABLE IF EXISTS public.fait_sante_annuelle
    ADD CONSTRAINT fait_sante_annuelle_id_pays_fkey FOREIGN KEY (id_pays)
    REFERENCES public.dim_pays (id_pays) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
